manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: efogdev
      url-base: https://github.com/efogdev
    - name: sekigon-gonnoc
      url-base: https://github.com/sekigon-gonnoc
    - name: hsgw
      url-base: https://github.com/hsgw
    - name: zettaface
      url-base: https://github.com/zettaface
    - name: caksoylar  # <-- led
      url-base: https://github.com/caksoylar

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml

    # PMW3222 ドライバ（外部モジュール）
    - name: zmk-paw3222-driver
      remote: sekigon-gonnoc
      revision: main

    # Sensor-rotation
    - name: zmk-feature-sensor_rotation
      remote: hsgw
      revision: main

    # Arrow-torabo
    - name: zmk-input-processor-keybind
      remote: zettaface
      revision: main

    # LED
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: v0.3


  self:
    path: config