manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: juichi50iii
      url-base: https://github.com/juichi50iii
    - name: zettaface
      url-base: https://github.com/zettaface
    - name: caksoylar
      url-base: https://github.com/caksoylar

  projects:
    - name: zmk
      remote: juichi50iii
      revision: 22c578f42229d6d54c7d7acda9ef24253f827f76
      import: app/west.yml

    - name: zmk-driver-paw3222
      remote: juichi50iii
      revision: main

    # Arrow-torabo
    - name: zmk-input-processor-keybind
      remote: zettaface
      revision: main

    # LED
    - name: zmk-rgbled-widget
      remote: juichi50iii
      revision: v0.3

    #　Axis-lock
    - name: zmk-axis-lock
      remote: juichi50iii
      revision: main

    # nurunuru
    - name: zmk-scroll-nurunuru
      remote: juichi50iii
      revision: 86751bfb3841e861f7a6489b024cddd6a2f0bc7f

  self:
    path: config
